<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.12.1 on win32)" generated="20240106 21:54:42.164" rpa="false" schemaversion="4">
<suite id="s1" name="Suites" source="C:\Users\USER\Desktop\Mobile Automation\suites">
<suite id="s1-s1" name="loginSuite" source="C:\Users\USER\Desktop\Mobile Automation\suites\loginSuite.robot">
<test id="s1-s1-t1" name="User should be able to login with valid credentials" line="7">
<kw name="Open Flight application" library="base">
<kw name="Open Application" library="AppiumLibrary">
<arg>remote_url=${REMOTE_URL}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>platformVersion=${PLATFORM_VERSION}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>appPackage=${APP_PACKAGE}</arg>
<arg>appActivity=${APP_ACTIVITY}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<msg timestamp="20240106 21:54:46.273" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000157893E8320&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20240106 21:54:48.344" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000015785A3B1A0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20240106 21:54:50.378" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000157893E8F50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20240106 21:54:52.416" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20240106 21:54:52.416" endtime="20240106 21:54:53.624"/>
</kw>
<msg timestamp="20240106 21:54:53.624" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20240106 21:54:53.630" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000157893E92E0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<status status="FAIL" starttime="20240106 21:54:44.020" endtime="20240106 21:54:53.632"/>
</kw>
<status status="FAIL" starttime="20240106 21:54:44.018" endtime="20240106 21:54:53.632"/>
</kw>
<kw name="Verify Home Page appears" library="homePage">
<status status="NOT RUN" starttime="20240106 21:54:53.636" endtime="20240106 21:54:53.636"/>
</kw>
<kw name="Click Sign In Button On Home Page" library="homePage">
<status status="NOT RUN" starttime="20240106 21:54:53.636" endtime="20240106 21:54:53.637"/>
</kw>
<kw name="Verify Login Appears" library="loginPage">
<status status="NOT RUN" starttime="20240106 21:54:53.637" endtime="20240106 21:54:53.637"/>
</kw>
<kw name="Input User Email On Login Page" library="loginPage">
<arg>${VALID_EMAIL}</arg>
<status status="NOT RUN" starttime="20240106 21:54:53.637" endtime="20240106 21:54:53.638"/>
</kw>
<kw name="Input User Password On Login Page" library="loginPage">
<arg>${VALID_PASSWORD}</arg>
<status status="NOT RUN" starttime="20240106 21:54:53.638" endtime="20240106 21:54:53.638"/>
</kw>
<kw name="Click Sign In Button On Login Page" library="loginPage">
<status status="NOT RUN" starttime="20240106 21:54:53.638" endtime="20240106 21:54:53.639"/>
</kw>
<kw name="Verify User Is Logged In" library="homePage">
<status status="NOT RUN" starttime="20240106 21:54:53.640" endtime="20240106 21:54:53.640"/>
</kw>
<kw name="Close Flight Application" library="base">
<status status="NOT RUN" starttime="20240106 21:54:53.641" endtime="20240106 21:54:53.641"/>
</kw>
<status status="FAIL" starttime="20240106 21:54:44.017" endtime="20240106 21:54:53.642">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000157893E92E0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</test>
<status status="FAIL" starttime="20240106 21:54:42.385" endtime="20240106 21:54:53.645"/>
</suite>
<status status="FAIL" starttime="20240106 21:54:42.184" endtime="20240106 21:54:53.647"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Suites">Suites</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="loginSuite">Suites.loginSuite</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240106 21:54:46.273" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000157893E8320&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20240106 21:54:48.344" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000015785A3B1A0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20240106 21:54:50.378" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000157893E8F50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20240106 21:54:53.624" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
